version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: crypto_db
    ports:
      - "5433:5432"  # <--- CHANGE THIS (Host Port : Container Port)
    volumes:
      - pg_data_final:/var/lib/postgresql/data

volumes:
  pg_data_final: